/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package locadora.view;

/**
 *
 * @author Usuario
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1Principal = new javax.swing.JPanel();
        jLabelLogo = new javax.swing.JLabel();
        jMenuBar1TelaPrincipal = new javax.swing.JMenuBar();
        jMenu1Locacao = new javax.swing.JMenu();
        jMenu1Alugar = new javax.swing.JMenu();
        jMenu1Consultar = new javax.swing.JMenu();
        jMenu2Cadastro = new javax.swing.JMenu();
        jMenu1Ator = new javax.swing.JMenu();
        jMenu1Cliente = new javax.swing.JMenu();
        jMenu1Filme = new javax.swing.JMenu();
        jMenu1Item = new javax.swing.JMenu();
        jMenu1Sair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vídeo Locadora Hora da Pipoca");

        jPanel1Principal.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1Principal.setName(""); // NOI18N
        jPanel1Principal.setPreferredSize(new java.awt.Dimension(700, 400));
        jPanel1Principal.setVerifyInputWhenFocusTarget(false);

        jLabelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1PrincipalLayout = new javax.swing.GroupLayout(jPanel1Principal);
        jPanel1Principal.setLayout(jPanel1PrincipalLayout);
        jPanel1PrincipalLayout.setHorizontalGroup(
            jPanel1PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1PrincipalLayout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addComponent(jLabelLogo)
                .addGap(65, 65, 65))
        );
        jPanel1PrincipalLayout.setVerticalGroup(
            jPanel1PrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1PrincipalLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabelLogo)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        jMenu1Locacao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon.png"))); // NOI18N
        jMenu1Locacao.setText("Locação");
        jMenu1Locacao.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenu1Alugar.setText("Alugar");
        jMenu1Alugar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu1Locacao.add(jMenu1Alugar);

        jMenu1Consultar.setText("Consultar");
        jMenu1Consultar.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu1Locacao.add(jMenu1Consultar);

        jMenuBar1TelaPrincipal.add(jMenu1Locacao);

        jMenu2Cadastro.setText("Cadastro");
        jMenu2Cadastro.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N

        jMenu1Ator.setText("Ator");
        jMenu1Ator.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu2Cadastro.add(jMenu1Ator);

        jMenu1Cliente.setText("Cliente");
        jMenu1Cliente.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu2Cadastro.add(jMenu1Cliente);

        jMenu1Filme.setText("Filme");
        jMenu1Filme.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu2Cadastro.add(jMenu1Filme);

        jMenu1Item.setText("Item");
        jMenu1Item.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenu2Cadastro.add(jMenu1Item);

        jMenuBar1TelaPrincipal.add(jMenu2Cadastro);

        jMenu1Sair.setText("Sair");
        jMenu1Sair.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jMenuBar1TelaPrincipal.add(jMenu1Sair);

        setJMenuBar(jMenuBar1TelaPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(jPanel1Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JMenu jMenu1Alugar;
    private javax.swing.JMenu jMenu1Ator;
    private javax.swing.JMenu jMenu1Cliente;
    private javax.swing.JMenu jMenu1Consultar;
    private javax.swing.JMenu jMenu1Filme;
    private javax.swing.JMenu jMenu1Item;
    private javax.swing.JMenu jMenu1Locacao;
    private javax.swing.JMenu jMenu1Sair;
    private javax.swing.JMenu jMenu2Cadastro;
    private javax.swing.JMenuBar jMenuBar1TelaPrincipal;
    private javax.swing.JPanel jPanel1Principal;
    // End of variables declaration//GEN-END:variables
}
